sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "10"
env:
    - PORT=80
    - SERVER_URL=http://stroids.io
install:
    - npm install
    - npm run build
script:
    - npm run start
